---
# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "pfeifdrauf"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email:  blog@pfeiffer.rocks
logo:  "logo.jpg"
cover: "background-bright.jpg"

name: 'Thomas Pfeiffer'
author: 'Thomas Pfeiffer'
#author_image: "/assets/images/author.jpg"

paginate: 5

url: "http://pfeiffer.rocks" # the base hostname & protocol for your site
baseurl: ""

assets:
  js_compressor:  uglifier
  css_compressor: sass
  cache:          true

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - LICENSE
  - .gitignore
  - .gitmodule
  - .ruby-gemset
  - .ruby-version

# social icons and sharing options
social:
  - icon: twitter
    url:  https://twitter.com/pfeiffdrauf
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: github
    url:  https://github.com/t-p
    desc: Find me on github
    share_url:
    share_title:
    share_link:

#  - icon: google-plus
#    url:  https://google.com/???
#    desc: Add me on google+
#    share_url:
#    share_title:
#    share_link:
